### ISSUE TITLE
Lists not being rendered

### ISSUE THREAD

**Issue by etuardu** [PierrePaul/html5-dopetrope#6]
Both ordered and unordered lists (`<ol>`, `<ul>`) are not being rendered, i.e. no numbers or bullets are displayed.
This seems to be due to a css rule contained in `/static/js/skel.min.js` (row 1, char 1104):

``` css
    ol,ul{list-style:none;}

```
